prefix=/usr
LIBPATH=$(prefix)/lib64

FILELIST_LIBS+=$(LIBPATH)/libboost_filesystem.a
FILELIST_LIBS+=$(LIBPATH)/libboost_system.a

lesson_1:
	g++ -O lesson_1.cpp -o lesson_1.bin 



#OPTIONS_LIBS+=$(LIBPATH)/libboost_program_options.a
#program_options:
#	g++ -O program_options.cpp -o program_options.bin $(OPTIONS_LIBS)
#
#
#REGEX_LIBS+=$(LIBPATH)/libboost_regex.a
#regex:
#	g++ -O regex.cpp -o regex.bin $(REGEX_LIBS)
#
#REGEX_MATCH_LIBS+=$(LIBPATH)/libboost_regex.a
#regex_match:
#	g++ -O regex_match.cpp -o regex_match.bin $(REGEX_MATCH_LIBS)
#
#REGEX_SPLIT_LIBS+=$(LIBPATH)/libboost_regex.a
#regex_split:
#	g++ -O regex_split.cpp -o regex_split.bin $(REGEX_SPLIT_LIBS)
